/** Chat UI — mock conversation data for Phase 3 */
import type { Conversation } from './types';

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    title: 'Rust async patterns',
    lastMessage: 'Here is an example using tokio::spawn…',
    updatedAt: new Date('2026-07-29T14:10:00Z'),
    messages: [
      {
        id: 'm1',
        role: 'user',
        content: 'Can you show me how to spawn concurrent tasks in Rust using Tokio?',
        timestamp: new Date('2026-07-29T14:05:00Z'),
      },
      {
        id: 'm2',
        role: 'assistant',
        content: [
          'Sure! Here\'s a concise example using `tokio::spawn` to run tasks concurrently:',
          '',
          '```rust',
          'use tokio::task;',
          '',
          '#[tokio::main]',
          'async fn main() {',
          '    let handle_a = task::spawn(async {',
          '        println!("Task A running");',
          '        42',
          '    });',
          '',
          '    let handle_b = task::spawn(async {',
          '        println!("Task B running");',
          '        "hello"',
          '    });',
          '',
          '    let (result_a, result_b) = tokio::join!(handle_a, handle_b);',
          '    println!("A returned: {}", result_a.unwrap());',
          '    println!("B returned: {}", result_b.unwrap());',
          '}',
          '```',
          '',
          'Key points:',
          '- `task::spawn` returns a `JoinHandle<T>` — you can `.await` it later.',
          '- `tokio::join!` runs both handles **concurrently** and waits for both to finish.',
          '- Each spawned task runs on the Tokio thread pool, so they may run in parallel on multi-core systems.',
          '',
          'If you need structured concurrency with cancellation, look into **`tokio::select!`** or the `tokio-util` crate\'s `CancellationToken`.',
        ].join('\n'),
        timestamp: new Date('2026-07-29T14:05:30Z'),
      },
      {
        id: 'm3',
        role: 'user',
        content: 'How do I handle errors from spawned tasks?',
        timestamp: new Date('2026-07-29T14:06:00Z'),
      },
      {
        id: 'm4',
        role: 'assistant',
        content: [
          '`JoinHandle::await` returns `Result<T, JoinError>`. A `JoinError` occurs when the task **panics** or is **cancelled**.',
          "Here's a pattern that propagates both task errors and join errors cleanly:",
          '',
          '```rust',
          'use tokio::task;',
          '',
          'async fn fetch_data(id: u32) -> anyhow::Result<String> {',
          '    if id == 0 {',
          '        anyhow::bail!("id must be non-zero");',
          '    }',
          '    Ok(format!("data-{id}"))',
          '}',
          '',
          '#[tokio::main]',
          'async fn main() -> anyhow::Result<()> {',
          '    let handles: Vec<_> = (0..4)',
          '        .map(|i| task::spawn(fetch_data(i)))',
          '        .collect();',
          '',
          '    for handle in handles {',
          '        match handle.await {',
          '            Ok(Ok(data))  => println!("Got: {data}"),',
          '            Ok(Err(e))    => eprintln!("Task error: {e}"),',
          '            Err(join_err) => eprintln!("Task panicked: {join_err}"),',
          '        }',
          '    }',
          '',
          '    Ok(())',
          '}',
          '```',
          '',
          '> **Tip:** Use `anyhow::Result` as the task return type so you can use `?` freely inside each task without boxing errors manually.',
        ].join('\n'),
        timestamp: new Date('2026-07-29T14:06:45Z'),
      },
    ],
  },
  {
    id: 'conv-2',
    title: 'React performance tips',
    lastMessage: 'Use useMemo and useCallback to avoid unnecessary re-renders.',
    updatedAt: new Date('2026-07-29T12:30:00Z'),
    messages: [
      {
        id: 'm5',
        role: 'user',
        content: 'My React app re-renders too often. What are the main tools to prevent unnecessary renders?',
        timestamp: new Date('2026-07-29T12:25:00Z'),
      },
      {
        id: 'm6',
        role: 'assistant',
        content: [
          'Great question! Here are the main tools React gives you:',
          '',
          '## `React.memo`',
          'Wraps a component so it only re-renders when its **props change** (shallow compare):',
          '',
          '```tsx',
          'const ExpensiveList = React.memo(function ExpensiveList({ items }: { items: string[] }) {',
          '  return <ul>{items.map(i => <li key={i}>{i}</li>)}</ul>;',
          '});',
          '```',
          '',
          '## `useMemo`',
          'Memoizes an **expensive computed value**:',
          '',
          '```tsx',
          'const sortedItems = useMemo(',
          '  () => [...items].sort((a, b) => a.localeCompare(b)),',
          '  [items]  // only recompute when items changes',
          ');',
          '```',
          '',
          '## `useCallback`',
          'Memoizes a **function reference** so child components don\'t re-render when the parent does:',
          '',
          '```tsx',
          'const handleClick = useCallback((id: string) => {',
          '  dispatch({ type: \'SELECT\', id });',
          '}, [dispatch]);',
          '```',
          '',
          '### When to reach for these?',
          '| Tool | Reach for it when… |',
          '|------|---------------------|',
          '| `memo` | A child renders often but its props rarely change |',
          '| `useMemo` | A computation takes >1 ms or produces a new object/array reference |',
          '| `useCallback` | Passing callbacks as props to memoised children |',
          '',
          '> **Warning:** Don\'t over-optimise. Profiler first, optimise second.',
        ].join('\n'),
        timestamp: new Date('2026-07-29T12:25:45Z'),
      },
      {
        id: 'm7',
        role: 'user',
        content: 'Is there a way to see which components are re-rendering without the DevTools extension?',
        timestamp: new Date('2026-07-29T12:28:00Z'),
      },
      {
        id: 'm8',
        role: 'assistant',
        content: [
          'Yes — a quick trick is to use a `useRef` counter inside the component:',
          '',
          '```tsx',
          'function DebugRenders({ name }: { name: string }) {',
          '  const renders = useRef(0);',
          '  renders.current += 1;',
          '  console.log("[" + name + "] render #" + renders.current);',
          '',
          '  return <div>{name}</div>;',
          '}',
          '```',
          '',
          'For a more reusable approach, extract it as a custom hook:',
          '',
          '```tsx',
          'function useRenderCount(label: string) {',
          '  const count = useRef(0);',
          '  count.current += 1;',
          '',
          '  if (import.meta.env.DEV) {',
          '    // eslint-disable-next-line no-console',
          '    console.debug("[renders] " + label + ": " + count.current);',
          '  }',
          '}',
          '',
          '// Usage:',
          'function MyComponent() {',
          '  useRenderCount("MyComponent");',
          '  return <div>...</div>;',
          '}',
          '```',
          '',
          'This works in any environment — no browser extension needed. Just remember to remove it',
          '(or guard with `import.meta.env.DEV`) before shipping to production.',
        ].join('\n'),
        timestamp: new Date('2026-07-29T12:29:00Z'),
      },
    ],
  },
  {
    id: 'conv-3',
    title: 'SQL query optimisation',
    lastMessage: 'Adding a composite index on (user_id, created_at) should help.',
    updatedAt: new Date('2026-07-28T09:15:00Z'),
    messages: [
      {
        id: 'm9',
        role: 'user',
        content: [
          'This query is slow. Can you help me optimise it?',
          '',
          '```sql',
          'SELECT * FROM orders',
          'WHERE user_id = 42',
          'ORDER BY created_at DESC',
          'LIMIT 20;',
          '```',
        ].join('\n'),
        timestamp: new Date('2026-07-28T09:10:00Z'),
      },
      {
        id: 'm10',
        role: 'assistant',
        content: [
          'The most impactful fix is a **composite index** on `(user_id, created_at)`. Here\'s why and how:',
          '',
          '```sql',
          '-- Add a composite index (run once)',
          'CREATE INDEX CONCURRENTLY idx_orders_user_created',
          '  ON orders (user_id, created_at DESC);',
          '```',
          '',
          '**Why this works:**',
          '1. PostgreSQL can do an **Index Scan** filtered to `user_id = 42` — no full table scan.',
          '2. Because the index already stores rows in `created_at DESC` order, the `ORDER BY` is free.',
          '3. `LIMIT 20` stops the scan after 20 rows — the database never touches the rest.',
          '',
          '**Before vs After (EXPLAIN ANALYZE):**',
          '',
          '| | Before | After |',
          '|---|---|---|',
          '| Scan type | Seq Scan | Index Scan |',
          '| Rows examined | ~500 000 | 20 |',
          '| Sort | External sort | None (index-ordered) |',
          '',
          'Also consider:',
          '- Replace `SELECT *` with only the columns you need — reduces I/O and network traffic.',
          '- Partition the table by `user_id` if it has hundreds of millions of rows.',
        ].join('\n'),
        timestamp: new Date('2026-07-28T09:11:30Z'),
      },
    ],
  },
];
